### ISSUE TITLE
The Problem Of The CPU Features

### ISSUE THREAD

**Issue by ryderkun** [filecoin-project/filecoin-ffi#131]
https://github.com/filecoin-project/filecoin-ffi/blob/d70d49a742cde20bda233dbc63abebda0e8e4406/install-filcrypto#L181

There is a problem with the judgment here. If there is "tpr_shadow" in the CPU Flags, then according to this judgment, deleting the left and right strings will also be "sha", then optimized will be true, but this is the Intel CPU.

I can solve this problem by pulling request

**Comment by cryptonemo** [comment]
See #132

**Comment by cryptonemo** [comment]
Resolved with #132
