### ISSUE TITLE
Leak detector checks

### ISSUE THREAD

**Issue by cryptonemo** [filecoin-project/filecoin-ffi#151]
CI leak detector checks take an hour or more to run.  We now run 2 configurations of it (both pairing and blst).  We should look into ways to speed this up.

**Comment by cryptonemo** [comment]
Noting that the runs are closer to 3-4 hours each now.

**Comment by vmx** [comment]
That's no longer the case, even with the leak detector the CI runs in a reasonable amount of time. Hence closing this issue.
