### ISSUE TITLE
Check for tar ball presence before downloading?

### ISSUE THREAD

**Issue by cryptonemo** [filecoin-project/filecoin-ffi#172]
Consider adding something like this:

https://github.com/filecoin-project/filecoin-ffi/commit/92ec33e1347d8a46c87c96c2734c798919baf23d?diff=unified&w=1

**Comment by vmx** [comment]
This issue has been open for a long time, but it doesn't seem that there's much interest in it, hence closing the issue. In case anyone is interested, feel free to open a PR.
