### ISSUE TITLE
error on macOS m1

### ISSUE THREAD

**Issue by dayu26** [filecoin-project/filecoin-ffi#175]
In 142aa2fd22941628274758d0003853a0d9543403
I got 
+ cargo +nightly build --release --no-default-features --features pairing,gpu
+ tee /var/folders/2j/5hjcsc6x1gg3t7gyzjt2z0cw0000gn/T/tmp.puwcJhUY
    Updating git repository `https://github.com/filecoin-project/rust-fil-proofs`
error: failed to get `filecoin-hashers` as a dependency of package `filecoin-proofs-api v6.1.0 (https://github.com/filecoin-project/rust-filecoin-proofs-api?branch=m1-portable#88804d20)`
    ... which is depended on by `filcrypto v0.7.5 (/Users/yuda/go/src/github.com/filecoin-project/lotus/extern/filecoin-ffi/rust)`

Caused by:
  failed to load source for dependency `filecoin-hashers`

Caused by:
  Unable to update https://github.com/filecoin-project/rust-fil-proofs?branch=m1-portable#48c7ee80

Caused by:
  object not found - no match for id (48c7ee80a247fa63bcb4c53676860085bb51f513); class=Odb (9); code=NotFound (-3)
+ rm -f /var/folders/2j/5hjcsc6x1gg3t7gyzjt2z0cw0000gn/T/tmp.puwcJhUY
make: *** [.install-filcrypto] Error 101

when I run "make lotus"  in 'file coin-project/lotus/extern/filecoin-ffi*m1-portable'

on my macOS Big Sur
11.2.1
base on m1

**Comment by cryptonemo** [comment]
I just rebased the branches (waiting on CI).  Please try again with the latest and let me know.

**Comment by dayu26** [comment]
okay  ;-)

**Comment by cryptonemo** [comment]
Just pushed the FFI dependency updates (only matters if you're not building from source with updated dependencies), but worth a shot now since it's been updated.

**Comment by dayu26** [comment]
It works! Thanks a lot!

**Comment by cryptonemo** [comment]
Great, thanks for re-testing!
