### ISSUE TITLE
Need Update to Latest Version

### ISSUE THREAD

**Issue by maweis1981** [filecoin-project/filecoin-ffi#184]
https://github.com/filecoin-project/filecoin-ffi/blob/8b97bd8230b77bd32f4f27e4766a6d8a03b4e801/rust/src/proofs/api.rs#L511

**Comment by cryptonemo** [comment]
Try running the latest version: https://github.com/filecoin-project/filecoin-ffi/blob/master/rust/src/proofs/api.rs#L521

**Comment by cryptonemo** [comment]
Closing due to lack of response.
