### ISSUE TITLE
does it support aarch64(arm64) system?

### ISSUE THREAD

**Issue by whhpc19891120** [filecoin-project/filecoin-ffi#199]
i have got a problem while compile lotus
####################################################

error: failed to run custom build command for `filcrypto v0.7.5 (/kingdom/lotus/extern/filecoin-ffi/rust)`

Caused by:
  process didn't exit successfully: `/kingdom/lotus/extern/filecoin-ffi/rust/target/release/build/filcrypto-b21c34c7f0029451/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Could not generate header: CargoMetadata("/kingdom/lotus/extern/filecoin-ffi/rust/Cargo.toml", Metadata(Output { status: ExitStatus(ExitStatus(25856)), stdout: "", stderr: "warning: Patch `opencl3 v0.2.4 (https://github.com/vmx/opencl3?branch=filecoin-ffi-v9-tmp-fix#80f4520a)` was not used in the crate graph.\nCheck that the patched package version and available features are compatible\nwith the dependency requirements. If the patch has a different version from\nwhat is locked in the Cargo.lock file, run `cargo update` to use the new\nversion. This may also occur with an optional dependency that is not enabled.\n Downloading crates ...\nwarning: spurious network error (2 tries remaining): [28] Timeout was reached (download of `fuchsia-cprng v0.1.1` failed to transfer more than 10 bytes in 30s)\nwarning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `aesni v0.10.0` within 30s)\n  Downloaded hmac v0.10.1\n  Downloaded hkdf v0.10.0\n  Downloaded rand_hc v0.2.0\n  Downloaded rand_hc v0.3.1\n  Downloaded wasi v0.10.2+wasi-snapshot-preview1\n  Downloaded output_vt100 v0.1.2\n  Downloaded kernel32-sys v0.2.2\n  Downloaded rand_core v0.4.2\n  Downloaded redox_syscall v0.2.10\n  Downloaded aesni v0.10.0\n  Downloaded fuchsia-cprng v0.1.1\n  Downloaded winapi v0.2.8\nwarning: spurious network error (2 tries remaining): [28] Timeout was reached (download of `winapi v0.3.9` failed to transfer more than 10 bytes in 30s)\nwarning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `paired v0.22.0` within 30s)\nwarning: spurious network error (2 tries remaining): [28] Timeout was reached (download of `winapi-x86_64-pc-windows-gnu v0.4.0` failed to transfer more than 10 bytes in 30s)\nwarning: spurious network error (2 tries remaining): [28] Timeout was reached (failed to download any data for `winapi-i686-pc-windows-gnu v0.4.0` within 30s)\nwarning: spurious network error (1 tries remaining): [28] Timeout was reached (download of `paired v0.22.0` failed to transfer more than 10 bytes in 30s)\nwarning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `winapi v0.3.9` within 30s)\nwarning: spurious network error (1 tries remaining): [28] Timeout was reached (download of `winapi-i686-pc-windows-gnu v0.4.0` failed to transfer more than 10 bytes in 30s)\nwarning: spurious network error (1 tries remaining): [28] Timeout was reached (failed to download any data for `winapi-x86_64-pc-windows-gnu v0.4.0` within 30s)\nerror: failed to download from `https://crates.io/api/v1/crates/winapi/0.3.9/download`\n\nCaused by:\n  [28] Timeout was reached (download of `winapi v0.3.9` failed to transfer more than 10 bytes in 30s)\n" }))', build.rs:9:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
+ rm -f /tmp/tmp.z2matGUEqQ
make[1]: *** [.install-filcrypto] Error 101
make[1]: Leaving directory `/kingdom/lotus/extern/filecoin-ffi'
make: *** [build/.filecoin-install] Error 2

**Comment by vmx** [comment]
Yes, aarch64 should work (and at least go beyond this error, which doesn't seem aarch64 related). In the error message I'm seeing timeouts. Can you please try to run it again? Can you please also provide information which version/commit of Lotus you use as a basis and provide the exact steps, so that we can try to reproduce.

**Comment by whhpc19891120** [comment]
> Yes, aarch64 should work (and at least go beyond this error, which doesn't seem aarch64 related). In the error message I'm seeing timeouts. Can you please try to run it again? Can you please also provide information which version/commit of Lotus you use as a basis and provide the exact steps, so that we can try to reproduce.

i have resloved this by cargo cleann  and cargo update,  thanks!
