### ISSUE TITLE
Building error on lotus v1.13.0 when FFI_BUILD_FROM_SOURCE

### ISSUE THREAD

**Issue by mathshero** [filecoin-project/filecoin-ffi#214]
We get source code of lotus v1.13.0.
1. _cd lotus_ directory and _make_, it succeeds
2. but _cd lotus/extern/filecoin-ffi_, then 
_rm rust/Cargo.lock_,
_make clean && FFI_BUILD_FROM_SOURCE=1 ./install-filcrypto_
it fails now.

![WechatIMG6](https://user-images.githubusercontent.com/39174874/142126834-38ed5a7c-7b65-453d-9bf9-1201674d9caa.jpeg)
<img width="990" alt="截屏2021-11-16 下午7 17 39" src="https://user-images.githubusercontent.com/39174874/142126851-77ccd27e-6bb2-4b54-9736-127d3820fe57.png">

**Comment by cryptonemo** [comment]
Try to use the `build.sh` script for building from source
