### ISSUE TITLE
Fix m1 Mac builds

### ISSUE THREAD

**Issue by cryptonemo** [filecoin-project/filecoin-ffi#216]
### Description

A build from source failure has been reported since the install script does not install the required `cargo lipo` tooling, whereas the CI scripting installs all required pre-reqs.  This shouldn't affect systems that already have all of the pre-reqs, but shouldn't fail if they are not present.

**Comment by shawnrader** [comment]
I have access to an m1 and can take a look at this.

**Comment by cryptonemo** [comment]
> I have access to an m1 and can take a look at this.

Great!  If you have details on any current issues, it would help.  At one point I went through and made sure all m1 builds were ok, but it's been a while since I've tested there.

**Comment by shawnrader** [comment]
The only issues I had building the variations listed in the readme.md on mac m1 were resolved with "brew install hwloc jq".  I will need to go through the build steps in config.yml to see if there are any additional issues there.

**Comment by cryptonemo** [comment]
Great, it's possible this is a stale/non-issue.

**Comment by shawnrader** [comment]
It looks like we are building both Intel MAC and M1 Mac binaries, but only packaging and publishing the Intel MAC versions.

**Comment by vmx** [comment]
I think this is fixed, if not, please re-open this issue.
