### ISSUE TITLE
GPU FFT failed! Falling back to CPU... Error: Ocl

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/filecoin-ffi#218]
**Describe the bug**
GPU gets error when starting on Snark processing after being scheduled on PC2 phase. Recovers after 4 minutes

**To Reproduce**

> 2020-08-07T23:33:32.275 INFO storage_proofs_core::compound_proof > vanilla_proof:finish
> 2020-08-07T23:33:32.308 INFO storage_proofs_core::compound_proof > snark_proof:start
> 2020-08-07T23:33:32.418 INFO bellperson::groth16::prover > Bellperson 0.9.2 is being used!
> 2020-08-07T23:34:30.234Z	INFO	markets	loggers/loggers.go:18	storage event	{"name": "ProviderEventDealPublished", "proposal CID": "bafyreibtp5t6ffsm5q5uodattf2xc6zs2nawi2nqdhv7knoww4dlqgi7rm", "state": "StorageDealStaged", "message": ""}
> 2020-08-07T23:34:30.316Z	INFO	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/client.go:204	rpc output message buffer	{"n": 2}
> 2020-08-07T23:34:30.397Z	INFO	sectors	storage-fsm@v0.0.0-20200730122205-d423ae90d8d4/sealing.go:123	Adding piece for deal 14602
> 2020-08-07T23:34:30.954Z	INFO	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/client.go:204	rpc output message buffer	{"n": 3}
> 2020-08-07T23:35:12.446 DEBUG bellperson::gpu::locks > Acquiring priority lock...
> 2020-08-07T23:35:12.446 DEBUG bellperson::gpu::locks > Priority lock acquired!
> 2020-08-07T23:35:12.660 INFO bellperson::gpu::locks > GPU is available for FFT!
> 2020-08-07T23:35:12.660 DEBUG bellperson::gpu::locks > Acquiring GPU lock...
> 2020-08-07T23:35:12.660 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2020-08-07T23:35:12.840 INFO bellperson::gpu::fft > FFT: 1 working device(s) selected.
> 2020-08-07T23:35:12.840 INFO bellperson::gpu::fft > FFT: Device 0: GeForce GTX 1080 Ti
> 2020-08-07T23:35:12.840 INFO bellperson::domain > GPU FFT kernel instantiated!
> 2020-08-07T23:35:13.376 WARN bellperson::gpu::locks > GPU FFT failed! Falling back to CPU... Error: Ocl Error: 
> 
> ################################ OPENCL ERROR ############################### 
> 
> Error executing function: clEnqueueNDRangeKernel("radix_fft")  
> 
> Status error code: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)  
> 
> Please visit the following url for more information: 
> 
> https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  
> 
> ############################################################################# 

[Repeats six times then]

> 2020-08-07T23:38:39.215 INFO storage_proofs_porep::stacked::vanilla::proof > persisting base tree_c 2/8 of length 153391689
> 2020-08-07T23:39:04.780 INFO bellperson::gpu::locks > GPU is available for Multiexp!
> 2020-08-07T23:39:04.780 DEBUG bellperson::gpu::locks > Acquiring GPU lock...
> 2020-08-07T23:39:04.780 DEBUG bellperson::gpu::locks > GPU lock acquired!
> 2020-08-07T23:39:05.020 INFO bellperson::gpu::multiexp > Multiexp: 1 working device(s) selected. (CPU utilization: 0)
> 2020-08-07T23:39:05.020 INFO bellperson::gpu::multiexp > Multiexp: Device 0: GeForce GTX 1080 Ti (Chunk-size: 6167411)
> 2020-08-07T23:39:05.020 INFO bellperson::multiexp > GPU Multiexp kernel instantiated!
> 

**Expected behavior**
I would like to see GPU cleanly engage in C2 Phase

**Screenshots**
Error description from reference:

> CL_MEM_OBJECT_ALLOCATION_FAILURE if there is a failure to allocate memory for data store associated with image or buffer objects specified as arguments to kernel.

**BEFORE**
`nvidia-smi`

> Fri Aug  7 23:28:26 2020       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
> | 58%   80C    P2   232W / 250W |   2003MiB / 11170MiB |    100%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A   3913035      C   lotus-miner                      2001MiB |
> +-----------------------------------------------------------------------------+
> 

**AFTER**
`nvidia-smi`

> Fri Aug  7 23:55:50 2020       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
> | 55%   76C    P2   228W / 250W |   3675MiB / 11170MiB |    100%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A   3913035      C   lotus-miner                      3673MiB |
> +-----------------------------------------------------------------------------+

**Version (run `lotus version`):**
`lotus version`
> Daemon:  0.4.3+git.460723d2+api0.8.1
> Local: lotus version 0.4.3+git.460723d2

**Additional context**
Running Ubuntu 20.04 server
GeForce GTX 1080 Ti running latest NVIDIA driver 450.57

_Related ENV variables used when building Lotus:_
FIL_PROOFS_MAXIMIZE_CACHING=1
BELLMAN_CUSTOM_GPU=GeForce GTX 1080 Ti:3584
FFI_BUILD_FROM_SOURCE=1
RUSTFLAGS=-C target-cpu=native -g
FIL_PROOFS_USE_GPU_TREE_BUILDER=1
RUST_BACKTRACE=full
RUST_LOG=debug
FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1

**Comment by vmx** [comment]
We've switched to another library for OpenCL, hence I'm closing this issue. If it's still happening, please re-open with updated information.
