### ISSUE TITLE
Add ARM build to CI

### ISSUE THREAD

**Issue by vmx** [filecoin-project/filecoin-ffi#274]
Currently we don't build the FFI on CI for ARM, but we should, to make sure we don't break it.

**Comment by airenas** [comment]
When building dockerfiles for lotus and boost on native *arm* platform (like Mac M1) we are forced to build **filecoin-ffi** from source as there are no prebuild Linux arm binaries. Having it would speed up the docker builds. 

Also it, perhaps, would require some change in *install-filcrypto* file: the line `local __release_name="${__repo_name}-$(uname)-${release_flag_name}"`. Now it according `uname` always downloads Linux binaries that are only *x86* compatible.

**Comment by LaurenSpiegel** [comment]
@vmx , any anticipated timing for this? if you need help in getting done, @airenas , do you have some time to help?

**Comment by airenas** [comment]
I see Draft [#287](https://github.com/filecoin-project/filecoin-ffi/pull/278), perhaps, you just need to finalize it.

**Comment by vmx** [comment]
@LaurenSpiegel Currently don't have any plans for implementing this (which is why I opened the issue). If there's a need for fixing this issue, perhaps @shawnrader may also be able to help.

**Comment by shawnrader** [comment]
I linked a pull request to add aarch64 Linux build, test, and publish to CI.  Apple M1/M2 support will need to be done as a different task and right now CircleCI only supports cross compilation from Intel Mac.

**Comment by shawnrader** [comment]
This issue for tracking mac M1 builds: https://github.com/filecoin-project/filecoin-ffi/issues/216
