### ISSUE TITLE
filecoin.h not updated after rebuild

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/filecoin-ffi#28]
When rebuilding from source on mac, `filecoin.h` is not updated (and I think the .a files neither), even when running `make clean`. Running `cargo clean` in the `rust` folder fixes it, but means you are rebuilding from scratch everytime.

**Comment by vmx** [comment]
Could this be related to https://github.com/filecoin-project/filecoin-ffi/pull/20?

**Comment by laser** [comment]
> Could this be related to #20?

@vmx - I recommend adding it back (along with relevant lines in the Makefile) and seeing if, after you add it back, the behavior described in #20 goes away (i.e. is fixed).

**Comment by vmx** [comment]
@laser #20 didn't get merged. I think if it would be merged, it would fix the problem.

**Comment by laser** [comment]
> I think if it would be merged, it would fix the problem.

Does `simplify-makefile` reproduce the behavior described in this issue after rebasing onto `master`? If it does not, then I think that what you think is correct.

**Comment by vmx** [comment]
When I created it, it did, but it was on Linux. So it would make sense to retry it on OSX.

**Comment by vmx** [comment]
@dignifiedquire with #20 merged, it should now work if you run a `make clean`. A `FFI_BUILD_FROM_SOURCE=1 make clean all` should do the job for you (@laser and I tried it locally on both OSX and Linux).
