### ISSUE TITLE
Missing ExecTraceBytes field in implicit message

### ISSUE THREAD

**Issue by strahe** [filecoin-project/filecoin-ffi#292]
Hi,
I found that when fvm apply the message, I can receive ExecTraceBytes

https://github.com/filecoin-project/filecoin-ffi/blob/acda280d74047ee7b247ffb8463cf29f1f108560/fvm.go#L120

But when fvm apply the implicit message, it is missing, is this expected?

https://github.com/filecoin-project/filecoin-ffi/blob/acda280d74047ee7b247ffb8463cf29f1f108560/fvm.go#L137

**Comment by Stebalien** [comment]
Nope, that looks like an oversight. Thanks for fixing it.
