### ISSUE TITLE
Rust unittests fail

### ISSUE THREAD

**Issue by shawnrader** [filecoin-project/filecoin-ffi#312]
Running "cargo test" from the 'rust' sub-directory results in the following errors:

test proofs::api::tests::test_faulty_sectors_v1 ... FAILED
test proofs::api::tests::test_faulty_sectors_v1_1 ... FAILED
test proofs::api::tests::test_sealing_versions ... FAILED

failures:

---- proofs::api::tests::test_faulty_sectors_v1 stdout ----
thread 'proofs::api::tests::test_faulty_sectors_v1' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[42]`: sector 42 should be faulty', src/proofs/api.rs:2644:13

---- proofs::api::tests::test_faulty_sectors_v1_1 stdout ----
thread 'proofs::api::tests::test_faulty_sectors_v1_1' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[42]`: sector 42 should be faulty', src/proofs/api.rs:2644:13

---- proofs::api::tests::test_sealing_versions stdout ----
thread 'proofs::api::tests::test_sealing_versions' panicked at 'seal_commit_phase2 failed: "No cached parameters found for stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-032d3138d22506ec0082ed72b2dcba18df18477904e35bafee82b3793b06832f [failure finding /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-032d3138d22506ec0082ed72b2dcba18df18477904e35bafee82b3793b06832f.params]\n\n

**Comment by shawnrader** [comment]
The same tests appear to fail going back over a year, I checked commit dc4e4e8dc9554dedb6f48304f7f0c6328331f9ec form may 21, and did not check any earlier.  Appears to be a long standing issue.

**Comment by shawnrader** [comment]
The issue appears to be that filecoin-proof-parameters must be downloaded first and pointed to be the FIL_PROOFS_PARAMETER_CACHE.  I had noticed the unittests were passing under CircleCI pipeline, so manually ran the same steps outlined in .circle/config.yml.
It would be a good idea to outline how to test the project locally in the project readme.md.  Possibly by just installing the CircleCI CLI to invoke the tests locally so it can be tested before pushing changes to github.

**Comment by Casheimo** [comment]
Thanks just trying to teach myself

**Comment by vmx** [comment]
If parameter files are there, things work, hence closing this issue.
