### ISSUE TITLE
Use newer Rust toolchain

### ISSUE THREAD

**Issue by terorie** [filecoin-project/filecoin-ffi#33]
`rust-toolchain` is currently set to an older `nightly` build.
Since the project is compatible with Rust 1.40, why not set it to `stable` or remove it?

**Comment by vmx** [comment]
I don't think we use any nightly features (it compiles at least with stable). @dignifiedquire Is there any reason not to simply switch to stable?

**Comment by terorie** [comment]
@vmx fyi, stable works for me. (as of Jan)

**Comment by ribasushi** [comment]
@vmx I think you fixed this, can close
