### ISSUE TITLE
failed to select a version for the requirement `funty = "~1.2"`

### ISSUE THREAD

**Issue by efreeworm** [filecoin-project/filecoin-ffi#334]
root@lotus/extern/filecoin-ffi $ ./build.sh 
error: failed to select a version for the requirement `funty = "~1.2"`
candidate versions found which didn't match: 2.0.0, 1.1.0, 1.0.1, ...
location searched: `rsproxy` index (which is replacing registry `crates-io`)
required by package `bitvec v0.22.3`
    ... which satisfies dependency `bitvec = "^0.22.3"` of package `ec-gpu-gen v0.3.0`
    ... which satisfies dependency `ec-gpu-gen = "^0.3.0"` of package `bellperson v0.22.0`
    ... which satisfies dependency `bellperson = "^0.22"` of package `filcrypto v0.7.5 (/lotus/extern/filecoin-ffi/rust)`
perhaps a crate was updated and forgotten to be re-vendored?

**Comment by vmx** [comment]
I'm on it.

**Comment by vmx** [comment]
@efreeworm have you removed the `Cargo.lock` file? With it in place it should still work.

**Comment by efreeworm** [comment]
**$ git clone https://github.com/filecoin-project/filecoin-ffi**
Cloning into 'filecoin-ffi'...
remote: Enumerating objects: 7634, done.
remote: Counting objects: 100% (640/640), done.
remote: Compressing objects: 100% (197/197), done.
remote: Total 7634 (delta 472), reused 589 (delta 439), pack-reused 6994
Receiving objects: 100% (7634/7634), 7.16 MiB | 86.00 KiB/s, done.
Resolving deltas: 100% (5156/5156), done.
**$ cd filecoin-ffi/**
**$ ./build.sh** 
go clean -cache -testcache .
rm -rf filcrypto.h filcrypto.pc libfilcrypto.a .install-filcrypto
rm -f ./runner
cd rust && cargo clean && cd ..
info: component 'rust-std' for target 'x86_64-apple-darwin' is up to date
info: component 'rust-std' for target 'aarch64-apple-darwin' is up to date
    Updating `rsproxy` index
error: failed to select a version for the requirement `funty = "~1.2"`
candidate versions found which didn't match: 2.0.0, 1.1.0, 1.0.1, ...
location searched: `rsproxy` index (which is replacing registry `crates-io`)
required by package `bitvec v0.22.3`
    ... which satisfies dependency `bitvec = "^0.22.3"` of package `ec-gpu-gen v0.3.0`
    ... which satisfies dependency `ec-gpu-gen = "^0.3.0"` of package `bellperson v0.22.0`
    ... which satisfies dependency `bellperson = "^0.22"` of package `filcrypto v0.7.5 (/lotus/extern/filecoin-ffi/rust)`
perhaps a crate was updated and forgotten to be re-vendored?

**$ git checkout 280c4f8b94fd46dc824a5c827dece73ec7fe3efd**
Note: checking out '280c4f8b94fd46dc824a5c827dece73ec7fe3efd'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 280c4f8 upgrade to fvm@3.0.0-alpha.5 and fvm_shared@3.0.0-alpha.8.

**$ ./build.sh** 
go clean -cache -testcache .
rm -rf filcrypto.h filcrypto.pc libfilcrypto.a .install-filcrypto
rm -f ./runner
cd rust && cargo clean && cd ..
info: component 'rust-std' for target 'x86_64-apple-darwin' is up to date
info: component 'rust-std' for target 'aarch64-apple-darwin' is up to date
    Updating `rsproxy` index
error: failed to select a version for the requirement `funty = "~1.2"`
candidate versions found which didn't match: 2.0.0, 1.1.0, 1.0.1, ...
location searched: `rsproxy` index (which is replacing registry `crates-io`)
required by package `bitvec v0.22.3`
    ... which satisfies dependency `bitvec = "^0.22.3"` of package `ec-gpu-gen v0.3.0`
    ... which satisfies dependency `ec-gpu-gen = "^0.3.0"` of package `bellperson v0.22.0`
    ... which satisfies dependency `bellperson = "^0.22"` of package `filcrypto v0.7.5 (/lotus/extern/filecoin-ffi/rust)`
perhaps a crate was updated and forgotten to be re-vendored?

**$ git show**
commit 280c4f8b94fd46dc824a5c827dece73ec7fe3efd (HEAD, tag: 280c4f8b94fd46dc, origin/release/lotus-v1.19.0)
Author: Raúl Kripalani <raul@protocol.ai>
Date:   Sat Oct 22 15:08:20 2022 +0100

    upgrade to fvm@3.0.0-alpha.5 and fvm_shared@3.0.0-alpha.8.

diff --git a/rust/Cargo.lock b/rust/Cargo.lock
index ed89bf2..8483331 100644
--- a/rust/Cargo.lock
+++ b/rust/Cargo.lock
@@ -144,9 +144,9 @@ checksum = "4cbbc9d0964165b47557570cce6c952866c2678457aca742aafc9fb771d30270"
 
 [[package]]
 name = "base64"
-version = "0.13.0"
+version = "0.13.1"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "904dfeac50f3cdaba28fc6f57fdcddb75f49ed61346676a78c4ffe55877802fd"
+checksum = "9e1b586273c5702936fe7b7d6896644d8be71e6314cfe09d3167c95f712589e8"
 
 [[package]]
 name = "bellperson"
@@ -800,9 +800,9 @@ dependencies = [
 
 [[package]]
 name = "cxx"
-version = "1.0.79"
+version = "1.0.80"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "3f83d0ebf42c6eafb8d7c52f7e5f2d3003b89c7aa4fd2b79229209459a849af8"
+checksum = "6b7d4e43b25d3c994662706a1d4fcfc32aaa6afd287502c111b237093bb23f3a"
 dependencies = [
  "cc",
  "cxxbridge-flags",
@@ -812,9 +812,9 @@ dependencies = [
 
 [[package]]
 name = "cxx-build"
-version = "1.0.79"
+version = "1.0.80"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "07d050484b55975889284352b0ffc2ecbda25c0c55978017c132b29ba0818a86"
+checksum = "84f8829ddc213e2c1368e51a2564c552b65a8cb6a28f31e576270ac81d5e5827"
 dependencies = [
  "cc",

**Comment by vmx** [comment]
Could you please try using `make` as outlined in the README instead of the `build.sh`?

**Comment by efreeworm** [comment]
set Cargo.toml is ok!
[patch.crates-io]
funty = { path = "../../../../funty-1.2.0" }

**Comment by Stebalien** [comment]
You should use the builtin `Cargo.lock` and build with `make` instead of patching anything.
