### ISSUE TITLE
Integration for new ec-gpu-gen available in rust-fil-proofs?

### ISSUE THREAD

**Issue by ramin-raeisi** [filecoin-project/filecoin-ffi#352]
Hello,

I wonder if there is a time plan available for a new filecoin-proofs-api release/tag integration which will be integrating rust-fil-proofs with new ec-gpu-gen functionality? This commit I mean, https://github.com/filecoin-project/rust-fil-proofs/commit/fbf3af067d9368fec2818f36fe2e2e7d5035d85b

Thank you in advance?

**Comment by vmx** [comment]
Cutting releases is a quite time intensive process. Currently there's not timeline for a next release. We cut releases whenever we see fit/a release is needed by downstream users like Lotus.

**Comment by Stebalien** [comment]
Once a release is cut, yes. cc @vmx.

But probably not till the new year.

**Comment by vmx** [comment]
@ramin-raeisi do you imply that you run into build issues? Current releases and master branches should work, if not, please let me know.

**Comment by vmx** [comment]
In the meantime there was a release with that version of `ec-gpu-gen`. Hence I'm closing this issue.
