### ISSUE TITLE
Deterministic BLS key generation

### ISSUE THREAD

**Issue by anorth** [filecoin-project/filecoin-ffi#38]
Implementations reasonably need to be able to generate deterministic keys for testing an other purposes.

Note this is already implemented in https://github.com/filecoin-project/bls-signatures/pull/17 but lost in repo churn.

**Comment by nikkolasg** [comment]
Fixed in #39

**Comment by frrist** [comment]
@nikkolasg can the deterministic private key generation method be exposed such that Go code can call it? Looking to use it in validation testing.

**Comment by vmx** [comment]
This was fixed with https://github.com/filecoin-project/filecoin-ffi/pull/58.
