### ISSUE TITLE
build failure on mac

### ISSUE THREAD

**Issue by zhiqiangxu** [filecoin-project/filecoin-ffi#403]
Here's some of the error output of `make`:

```
'+adx' is not a recognized feature for this target (ignoring feature)
'+adx' is not a recognized feature for this target (ignoring feature)
'+adx' is not a recognized feature for this target (ignoring feature)
'+avx2' is not a recognized feature for this target (ignoring feature)
'+avx2' is not a recognized feature for this target (ignoring feature)
'+adx' is not a recognized feature for this target (ignoring feature)
'+adx' is not a recognized feature for this target (ignoring feature)
'+avx2' is not a recognized feature for this target (ignoring feature)
'+avx2' is not a recognized feature for this target (ignoring feature)
'+avx2' is not a recognized feature for this target (ignoring feature)
'+adx' is not a recognized feature for this target (ignoring feature)
'+avx2' is not a recognized feature for this target (ignoring feature)
'+adx' is not a recognized feature for this target (ignoring feature)
'+avx2' is not a recognized feature for this target (ignoring feature)
'+adx' is not a recognized feature for this target (ignoring feature)
'+avx2' is not a recognized feature for this target (ignoring feature)
error[E0463]: can't find crate for `core`
  |
  = note: the `aarch64-apple-darwin` target may not be installed
  = help: consider downloading the target with `rustup target add aarch64-apple-darwin`

error[E0463]: can't find crate for `compiler_builtins`
```

Host info: `MacBook Pro (16-inch, 2019), i386`

**UPDATE**

After removing `aarch64-apple-darwin` from [this line](https://github.com/filecoin-project/filecoin-ffi/blob/d50c7944d508d61b8f5ff2dd9cf35ee8e30ad6bb/install-filcrypto#L167), it compiles.

**Comment by vmx** [comment]
Instead of removing that line you could also try `rustup target add aarch64-apple-darwin` instead. Does that also work?

**Comment by zhiqiangxu** [comment]
> Instead of removing that line you could also try `rustup target add aarch64-apple-darwin` instead. Does that also work?

Yeah I tried that and didn't work.

**Comment by vmx** [comment]
@zhiqiangxu I've totally missed the host information you provided. The reason is [that if statement](https://github.com/filecoin-project/filecoin-ffi/blob/d50c7944d508d61b8f5ff2dd9cf35ee8e30ad6bb/install-filcrypto#LL165C45-L165C53). It tries to build kind of a "universal" binary, for x86 as well as ARM.

You mention your host is `i386` (I've missed that information when I previously read the issue). I guess it's 64-bit though? Can you please run a `uname -s` and `uname -m` on your terminal an post your output here? Just for confirmation.

When you successfully ran `rustup target add aarch64-apple-darwin`, do you still get the same error message?

**Comment by zhiqiangxu** [comment]
> @zhiqiangxu I've totally missed the host information you provided. The reason is [that if statement](https://github.com/filecoin-project/filecoin-ffi/blob/d50c7944d508d61b8f5ff2dd9cf35ee8e30ad6bb/install-filcrypto#LL165C45-L165C53). It tries to build kind of a "universal" binary, for x86 as well as ARM.
> 
> You mention your host is `i386` (I've missed that information when I previously read the issue). I guess it's 64-bit though? Can you please run a `uname -s` and `uname -m` on your terminal an post your output here? Just for confirmation.
> 
> When you successfully ran `rustup target add aarch64-apple-darwin`, do you still get the same error message?

```
% uname -s
Darwin
% uname -m
x86_64
```

Yeah I still get the same error message after successfully ran `rustup target add aarch64-apple-darwin`.

**Comment by zhiqiangxu** [comment]
> Does the `build.sh` script work? That was intended to install required dependencies the first time

The `build.sh` doesn't seem to work:

```
% ./build.sh 
go clean -cache -testcache
rm -rf filcrypto.h filcrypto.pc libfilcrypto.a .install-filcrypto
rm -f ./runner
cd rust && cargo clean && cd ..
cat: rust-toolchain: No such file or directory
error: error: The argument '--toolchain <toolchain>' requires a value but none was supplied

For more information try --help
```

**Comment by vmx** [comment]
You can fix this by changing those two lines:

https://github.com/filecoin-project/filecoin-ffi/blob/master/build.sh#L8-L9

from `$(cat rust-toolchain)` to `$(cat rust-toolchain.toml)`

**Comment by zhiqiangxu** [comment]
> You can fix this by changing those two lines:
> 
> https://github.com/filecoin-project/filecoin-ffi/blob/master/build.sh#L8-L9
> 
> from `$(cat rust-toolchain)` to `$(cat rust-toolchain.toml)`

This time it reports:

```
% ./build.sh 
go clean -cache -testcache
rm -rf filcrypto.h filcrypto.pc libfilcrypto.a .install-filcrypto
rm -f ./runner
cd rust && cargo clean && cd ..
error: toolchain '[toolchain]' does not support components: [toolchain] is a custom toolchain
```

**Comment by zhiqiangxu** [comment]
> That script shouldn't be used anyway ;) So let's look at it again from another perspective.
> 
> Can you please run (from within the `fielcoin-ffi/rust` directory): `rustup show` and paste the output here. This is in order to double check that the toolchain is picked up correctly.

```
% rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/xxx/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-2022-05-09-x86_64-apple-darwin
nightly-2022-10-03-x86_64-apple-darwin
nightly-2022-12-10-x86_64-apple-darwin
nightly-2023-01-21-x86_64-apple-darwin
nightly-x86_64-apple-darwin
1.56.0-x86_64-apple-darwin
1.57.0-x86_64-apple-darwin
1.59.0-x86_64-apple-darwin
1.60.0-x86_64-apple-darwin
1.62.1-x86_64-apple-darwin
1.64.0-x86_64-apple-darwin
1.67.1-x86_64-apple-darwin

active toolchain
----------------

1.67.1-x86_64-apple-darwin (overridden by '/Users/xxx/Desktop/github/filecoin-tool/extern/filecoin-ffi/rust/rust-toolchain.toml')
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```

**Comment by vmx** [comment]
It doesn't list `aarch64-apple-darwin`. Can you try again to run `rustup target add aarch64-apple-darwin` from with the `filecoin-ffi/rust` directory?

**Comment by zhiqiangxu** [comment]
> It doesn't list `aarch64-apple-darwin`. Can you try again to run `rustup target add aarch64-apple-darwin` from with the `filecoin-ffi/rust` directory?

```
% rustup target add aarch64-apple-darwin
info: downloading component 'rust-std' for 'aarch64-apple-darwin'
info: installing component 'rust-std' for 'aarch64-apple-darwin'
 27.6 MiB /  27.6 MiB (100 %)  14.3 MiB/s in  1s ETA:  0s
% rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/xxx/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-2022-05-09-x86_64-apple-darwin
nightly-2022-10-03-x86_64-apple-darwin
nightly-2022-12-10-x86_64-apple-darwin
nightly-2023-01-21-x86_64-apple-darwin
nightly-x86_64-apple-darwin
1.56.0-x86_64-apple-darwin
1.57.0-x86_64-apple-darwin
1.59.0-x86_64-apple-darwin
1.60.0-x86_64-apple-darwin
1.62.1-x86_64-apple-darwin
1.64.0-x86_64-apple-darwin
1.67.1-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
x86_64-apple-darwin

active toolchain
----------------

1.67.1-x86_64-apple-darwin (overridden by '/Users/xxx/Desktop/github/filecoin-tool/extern/filecoin-ffi/rust/rust-toolchain.toml')
rustc 1.67.1 (d5a82bbd2 2023-02-07)

**Comment by vmx** [comment]
That looks good. Does the "make" now work?

**Comment by zhiqiangxu** [comment]
> That looks good. Does the "make" now work?

It's compiling now, the key point seems to be that I need to run `rustup target add aarch64-apple-darwin` under the `rust` directory, otherwise `make` won't pick it up?

**Comment by vmx** [comment]
> the key point seems to be that I need to run `rustup target add aarch64-apple-darwin` under the `rust` directory

That's really strange. Usually globally installed toolchains (when you run the `rustup` command somewhere else) should pick it up just fine.

**Comment by zhiqiangxu** [comment]
> > the key point seems to be that I need to run `rustup target add aarch64-apple-darwin` under the `rust` directory
> 
> That's really strange. Usually globally installed toolchains (when you run the `rustup` command somewhere else) should pick it up just fine.

I tried to run `rustup target add aarch64-apple-darwin` at the root directory, it also works this time. So I can't reproduce the problem I met previously...

**Comment by vmx** [comment]
Glad to hear that your problem is solved. I'll close this issue as I think the instructions from the original error message are clear enough. I guess we'll never find out what the problem on your machine was.
