### ISSUE TITLE
Releasing MacOS prebuilts will break in June 2024

### ISSUE THREAD

**Issue by vmx** [filecoin-project/filecoin-ffi#420]
[CircleCI is sunsetting all Intel MacOS machines in 2024](https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718). Currently we use such a machine to create universal binaries.

We should switch to an ARM based machine and cross-compile to Intel from there (if that's possible, I don't know much about MacOS).

**Update**: the sunsetting was postponed till June 2024.

**Comment by galargh** [comment]
https://github.com/filecoin-project/filecoin-ffi/blob/62960ca63d5fb1649ad95a947182175bbd5f11e8/install-filcrypto#L162-L164 suggests that it might not be possible.

Is dropping darwin/amd64 support an option?

Alternatively, let me know if you wanted us to look into setting up self-hosted Apple Intel runners.

**Comment by vmx** [comment]
A possible fix is at https://github.com/filecoin-project/filecoin-ffi/pull/424/.
