### ISSUE TITLE
Releases are triggered by code review

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/filecoin-ffi#469]
## Done Criteria
1. The release steps outlined in https://github.com/filecoin-project/filecoin-ffi#release-process can be followed without requiring manual clicking in the GitHub UI.  Instead, releases should occur as a result of an approved PR.
2. The release description should be populated with the GitHub-generated release notes.  (This repo doesn't have an accurate/updated CHANGELOG).

## Why Important
The release process in https://github.com/filecoin-project/filecoin-ffi#release-process doesn't have any peer review.  Mistakes can get made.  Mistagging has happened in the past and can't be reverted.  This is usually fixed by just doing another release, but this adds unnecessary confusion.  

## User/Customer
Maintainers

## Notes
1. Releases should also be clear and not have a duplicate asset-dedicated release.

**Comment by BigLep** [comment]
This is being addressed by https://github.com/filecoin-project/filecoin-ffi/pull/473

**Comment by BigLep** [comment]
Now the work is in https://github.com/filecoin-project/filecoin-ffi/pull/475

**Comment by rjan90** [comment]
Closing as completed since: https://github.com/filecoin-project/filecoin-ffi/pull/475, and we also fixed the follow-ups:

- https://github.com/filecoin-project/filecoin-ffi/pull/488
- https://github.com/filecoin-project/filecoin-ffi/pull/492
