### ISSUE TITLE
filecoin-ffi Release v1.30.0 (nv24)

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/filecoin-ffi#489]
This is a tracking issue for the filecoin-ffi Release that corresponds with [Lotus v1.30.0](https://github.com/filecoin-project/lotus/issues/12480), which is the minimum functionality needed for nv24.

Dependencies before merging:
- [ ] 

This will follow https://github.com/filecoin-project/filecoin-ffi/blob/master/RELEASE.md

**Comment by rjan90** [comment]
Closing as this release has been published here: https://github.com/filecoin-project/filecoin-ffi/releases/tag/v1.30.0
