### ISSUE TITLE
filecoin-ffi Release v1.31.0 (nv24++)

### ISSUE THREAD

**Issue by BigLep** [filecoin-project/filecoin-ffi#490]
This is a tracking issue for the filecoin-ffi Release that corresponds with [Lotus v1.31.0](https://github.com/filecoin-project/lotus/issues/12344), which has the functionality needed for nv24 plus additional changes.  This should have everything from https://github.com/filecoin-project/filecoin-ffi/issues/489 plus the additional dependencies.

Dependencies before merging:
- [x] https://github.com/filecoin-project/filecoin-ffi/issues/489
- [x] https://github.com/filecoin-project/filecoin-ffi/pull/484
- [x] https://github.com/filecoin-project/filecoin-ffi/pull/485

This will follow https://github.com/filecoin-project/filecoin-ffi/blob/master/RELEASE.md

**Comment by rjan90** [comment]
The first release candidate of filecoin-ffi has been published here: https://github.com/filecoin-project/filecoin-ffi/releases/tag/v1.31.0-rc1
