### ISSUE TITLE
how to make filecoin-ffi for ios?

### ISSUE THREAD

**Issue by SzeChuanChilliSauce** [filecoin-project/filecoin-ffi#77]
how to make filecoin-ffi for ios?

**Comment by magik6k** [comment]
You can try building in from sources, and passing some flags to the rust compiler like this:

```
FFI_BUILD_FROM_SOURCE=1 RUSTFLAGS='-C target-cpu=native' make clean deps build
```

(I'm not sure how cross-compiling rust for iOS works, you may need to exit some scripts in `extern/filecoin-ffi/rust/scripts`)

**Comment by apple94586** [comment]
> You can try building ffi from sources, and passing some flags to the rust compiler like this:
> 
> ```
> FFI_BUILD_FROM_SOURCE=1 RUSTFLAGS='-C target-cpu=native' make clean deps build
> ```
> 
> (I'm not sure how cross-compiling rust for iOS works, you may need to exit some scripts in `extern/filecoin-ffi/rust/scripts`)

Where should I configure aarch64-apple-ios and then build the static library to support aarch64-apple-ios
