### ISSUE TITLE
Proposal: A (parameter) versioned filecoin-ffi API

### ISSUE THREAD

**Issue by laser** [filecoin-project/filecoin-ffi#86]
The following has been moved from [a Slack conversation](https://filecoinproject.slack.com/archives/CEGB67XJ8/p1588879787172900) on May 7.

@dignifiedquire @icorderi @whyrusleeping @anorth 

## I think that the following is true:

Any change to the parameter version, regardless of whether it requires a code API change, is a breaking change (e.g. a verifying node which receives a v30 winning PoSt won't be able to verify it with their v29 verify_winning_post function) from the perspective of a libfilcrypto consumer today. Furthermore, there is no way for a node to link multiple versions of libfilcrypto when building their node (overlapping symbols from multiple copies of the Rust standard library, for example).

## I think we should do the following:

The libfilcrypto library should expose a set of proofs functions (seal, verify, whatever) per parameter version, up to some defined number of parameter versions (let's say that we start out with N=3) which we all agree to support. I think that filecoin-ffi should import N versions (identified by Git commit) of the filecoin-proofs crate, and should provide parameter version-prefixed functions in the filcrypto.h file, e.g. v27_fil_verify_winning_post.

## Why would we do this?

The protocol will map a range of epochs to a proofs protocol version (such as V1). The nodes will need to map one of these protocol versions (such as V1) to a set of libfilcrypto functions (such as v27_fil_verify_winning_post), and will also be responsible for knowing the current parameter version.

If we give the nodes the ability to pick (within a protocol version) a set of functions appropriate for their parameter version, we allow the nodes a migration path from one protocol version to the other as well as from one parameter version to the other. This approach would also allow for a more finely-grained bug fix-deployment pipeline (we could hotfix v42 while continuing to support v43).

Thoughts?

**Comment by laser** [comment]
@dignifiedquire 

> sure, but I want to make it clear that I have not seen any reason so far that suggest we need more api surface and will likely not have time to think about this more for a while
> 
> and that shipping unsupported versions of the protocol is a security risk asfaiu what you suggest in the proposal above

I believe that adding API surface area - to support multiple, concurrent proof parameter versions (e.g. v25, v26) - is to allow us deploy new proofs software to the node w/out breaking the previous software. This gives nodes a smoother upgrade path than what we have today.

**Comment by anorth** [comment]
I agree with the premises. I think an appropriate API for FFI to expose is a set of functions per parameter version, as you suggest. This is necessary for any upgrade to be consumable into a running network: the whole chain history must be verifiable. For testing this, we also need to continue to be able to create proofs with older versions so we can then test they are correctly verified.

I don't quite know what "filecoin-ffi should import N versions of the filecoin-proofs crate" means. My primary recommendation would be that the underlying Rust proofs library also continues to directly support all proof versions used in a live network, probably by the same pattern of a set of functions per proof-parameters version. I think it would be super painful for integrators to have to hunt through multiple different source trees of the "same" library to trace the code they are running. Even if superceded by a new proof version, the older ones are still first-class requirements of the running network and should be treated as such by the proofs library.

**Comment by laser** [comment]
> My primary recommendation would be that the underlying Rust proofs library also continues to directly support all proof versions used in a live network, probably by the same pattern of a set of functions per proof-parameters version.

What you recommend is different than what I recommend in an important way: It would require rust-fil-proofs ("the underlying Rust proofs library") to support multiple Groth parameter versions. The approach which I proposed does not have this property; the filecoin-ffi project would import various versions (Git commits) of the underlying Rust proofs library whose functions it would expose by prepending a parameter version-prefix (e.g. `v27_verify_seal`). 

The approach which I propose will not be optimal for Rust implementations, as Rust implementations will not use filecoin-ffi. The approach which you propose is more work for the maintainers of rust-fil-proofs and less work for the maintainers of filecoin-ffi.

**Comment by vmx** [comment]
I dare to close this issue as this proposal wasn't discussed for years, and also we haven't had new parameter versions since mainnet launch.
