### ISSUE TITLE
Replace minerID abi.ActorID parameters with address type

### ISSUE THREAD

**Issue by anorth** [filecoin-project/filecoin-ffi#92]
A bunch of functions in proofs.go accept a miner ID parameter as an actor ID. This id is then turned into a "prover id" by creating an ID address and then extracting its payload. But in implementations, all call sites started out with an ID address in the first place and had to extract the actor ID from it in order to call these functions.

Change the functions to just accept an address, and perhaps add a precondition that it is of protocol `address.ID` in order to fail fast if it's not.

**Comment by rjan90** [comment]
@anorth Is this still worth keeping open, or can we close this ticket?

**Comment by anorth** [comment]
It's probably entrenched enough not to be worthwhile four years later.
